version: '3.4'

services:
  docspell-addon-example-debug:
    image: tiborrr/docspell-addon-example-debug:latest
    container_name: docspell-addon-example-debug
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
