meta:
  name: "docspell-addon-example"
  version: "0.8.0"
  description: |
    This is a minimal example of a docspell addon. It does nothing but print Hello and the argument that was passed to it.
triggers:
  - final-process-item
runner:
  docker:
    enable: true
    image: tiborrr/docspell-addon-example:0.8.0
options:
  networking: false
  collectOutput: true